name: Build Rust Doc And Run tests

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build doc
        run: |
          rustup target add riscv64gc-unknown-none-elf
          rustup component add llvm-tools-preview
          rustup component add rust-src
          cd os
          cargo doc --no-deps --verbose
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./os/target/riscv64gc-unknown-none-elf/doc
          destination_dir: ${{ github.ref_name }}
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install QEMU
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build -y
          [ ! -d qemu-6.1.0 ] && wget https://download.qemu.org/qemu-6.1.0.tar.xz \
            && tar xJf qemu-6.1.0.tar.xz > /dev/null \
            && cd qemu-6.1.0 && ./configure --target-list=riscv64-softmmu && cd ..
          cd qemu-6.1.0 && sudo make install -j
          qemu-system-riscv64 --version
      - name: Run usertests
        run: |
          cd os && make run TEST=1
          

          
      